apiVersion: v2
name: envoy-gateway
description: The Helm chart for Envoy Gateway
type: application
version: v2.2.1
appVersion: "latest"

dependencies:
  # Community Envoy Gateway
  - name: gateway-helm
    version: v1.8.1
    repository: "file://charts/gateway-helm"
